[[Binutils]]
arch = "aarch64"
git-tree-sha1 = "462e426e4e55b85770509a5ac5021f057a14ec93"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "8ec3c34bed02f9f9d4c3c9615c1457c26081dae373085ad354be36ae90fdab18"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.39.0+0/Binutils.v2.39.0.aarch64-linux-gnu.tar.gz"
[[Binutils]]
arch = "aarch64"
git-tree-sha1 = "120b2f55b815a586fd2dc880f2e8d4c339bd2d88"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "4b8e3b146d9ba64d5bfdabe39824d4cd50fd79f0595e66765970f1cbb84fc9bd"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.39.0+0/Binutils.v2.39.0.aarch64-linux-musl.tar.gz"
[[Binutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8b4a5bb430d0e7b9d77f3995d83b07e588449df1"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "2173c9e12575521ee72f43b3d76e0ac97eaeeeba6fedca489b278566f186108c"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.39.0+0/Binutils.v2.39.0.armv6l-linux-gnueabihf.tar.gz"
[[Binutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "51afb9d8b11bff53764b30264d25749f44957417"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "9260f3e6dca633178af2e0544dc4404f9547b3732363475f699abc3fd22c95af"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.39.0+0/Binutils.v2.39.0.armv6l-linux-musleabihf.tar.gz"
[[Binutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "41f04dbaf6da2e96f21bb8c8dc2aa03beee10023"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "af1e6b0fadfc1c9cd7707d61268fed62d2eaff81e81b937b423a212376e84cad"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.39.0+0/Binutils.v2.39.0.armv7l-linux-gnueabihf.tar.gz"
[[Binutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "54f1dedabe76879f1e72788ce8cfa4c6929c1faa"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "5a75c33136cd9a6b3400066197abec558be2517a385d3d455212eff75d6e4308"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.39.0+0/Binutils.v2.39.0.armv7l-linux-musleabihf.tar.gz"
[[Binutils]]
arch = "i686"
git-tree-sha1 = "0cecd5dea5dced8709e23fe12648373937abd3ed"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "2ff57573e9120b2d0c9cf828abfcfc66880a680bdeeaca8c754d507b76bb43da"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.39.0+0/Binutils.v2.39.0.i686-linux-gnu.tar.gz"
[[Binutils]]
arch = "i686"
git-tree-sha1 = "018ba08e5e7638f157cd0b65f6b0d01436702536"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "bcaef3f79ec48a4e714c9a48ed3678f68e7988919210c0e734f1dee43431889b"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.39.0+0/Binutils.v2.39.0.i686-linux-musl.tar.gz"
[[Binutils]]
arch = "powerpc64le"
git-tree-sha1 = "68489305c0889ae7938a2b31d1473c025eada369"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "427f02b0e16fc4ea7094ba1a7a70ecad0f21b04760c1d7ab673fc28f942996aa"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.39.0+0/Binutils.v2.39.0.powerpc64le-linux-gnu.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "d456da5798a3960c18cdd812d11d6c162fbc0c2f"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "053347a1e3bae0eff7f4b8156675437cd58860dcd54c8f844f9b99f59ebdc991"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.39.0+0/Binutils.v2.39.0.x86_64-linux-gnu.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "f2eb4c5ef26e60b1d8a722624a174b7755e10b8f"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "1dbbbc67324bf74754fe58128ae062e9cbe62dfc747b649478fb9eecf5bee55e"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.39.0+0/Binutils.v2.39.0.x86_64-linux-musl.tar.gz"
