[[Binutils]]
arch = "aarch64"
git-tree-sha1 = "35121db9fa6b803f6e9ffb433dd8afeeaffd10d5"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "81dac00db433bc080142ae65aedfccac6ab22288ee9174346108fc303cd21a89"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.41.0+1/Binutils.v2.41.0.aarch64-linux-gnu.tar.gz"
[[Binutils]]
arch = "aarch64"
git-tree-sha1 = "43b9e2177325f71a3715ea9c594c334cecc1308c"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "d0c77fcea07b74cb29eb7ef24c65c8ce6bd3755402452a9b486c03279ab07628"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.41.0+1/Binutils.v2.41.0.aarch64-linux-musl.tar.gz"
[[Binutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "87f492a1e943ed792f4b818dd9f9a98e32f078a6"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "17d8b08452fd263b30fc162d6c4f99f6cd235eb8007e8b3c6dd8270c81e82b88"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.41.0+1/Binutils.v2.41.0.armv6l-linux-gnueabihf.tar.gz"
[[Binutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c0ca84dd9d0f97e69c1cc2f55dff3108062bf226"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "1d49911cd92bee002f93b86f92c389b2bcd29319c3929202fd41a86a46f58031"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.41.0+1/Binutils.v2.41.0.armv6l-linux-musleabihf.tar.gz"
[[Binutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e52aaac5f1220ad9950db73e02ab666a77b033c9"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "a7e199ab08fea76914d0cc016753ffa7d3c59f731380b28d0afe0441fc36c22d"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.41.0+1/Binutils.v2.41.0.armv7l-linux-gnueabihf.tar.gz"
[[Binutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b623c87895ba9b7d0c5925e33dd21792e6b3f242"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "7ccd2baa84f9c908ef29c6b7af9eaa6ded05b724bd0aca24d326690756fd3e6d"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.41.0+1/Binutils.v2.41.0.armv7l-linux-musleabihf.tar.gz"
[[Binutils]]
arch = "i686"
git-tree-sha1 = "1022712cb0f9e4dbc47dcec0317ccb8817a3e89f"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "d750c0d0b681dc5ca6619419b048a34c18aa8746f478c946d4fddf5d5e8cab1f"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.41.0+1/Binutils.v2.41.0.i686-linux-gnu.tar.gz"
[[Binutils]]
arch = "i686"
git-tree-sha1 = "9b97dc76c2bc9002cb110c03f91ce98e30a5c2d0"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "bf97b64f03cc7a69a0f13f4bf573607c3d4f71c85aa37c521b8de17c9808b263"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.41.0+1/Binutils.v2.41.0.i686-linux-musl.tar.gz"
[[Binutils]]
arch = "powerpc64le"
git-tree-sha1 = "ae918a2b6ff46d15cfefdd7c8870a89be21c7331"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "031402717e72e6739b2f5da5d9947708dd9da12bf4ba6cc3a02af37e396c6ee6"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.41.0+1/Binutils.v2.41.0.powerpc64le-linux-gnu.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "d58ba453e687d6a22f6ed6d0d0e122f8ad9accaa"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "ccbc24dab26d3d35bf3e06c9843f0f391387742726943ef7314fee633922efb3"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.41.0+1/Binutils.v2.41.0.x86_64-linux-gnu.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "9e7be46e2a8abd71b360a37c8a5810c858e49b78"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "f961e8c6731826f07b2c2e68ffff1ba0e5dae689c798725b8f2c90c618448c5d"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.41.0+1/Binutils.v2.41.0.x86_64-linux-musl.tar.gz"
