[[Binutils]]
arch = "aarch64"
git-tree-sha1 = "bc8cad7631e1c023840dcc30ed5308dbb4c26786"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "5cc6a68055513c646b48ac1a5287ee4c852674d4473fb28a5bde48c272eebb6d"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.45.0+0/Binutils.v2.45.0.aarch64-linux-gnu.tar.gz"
[[Binutils]]
arch = "aarch64"
git-tree-sha1 = "d11bc9f94074f7cb760d101e9492399ecd4f002a"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "d2474baf08ed4e6e5233b93416053588b8c88633f406c5eaebb1df93ded303b5"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.45.0+0/Binutils.v2.45.0.aarch64-linux-musl.tar.gz"
[[Binutils]]
arch = "aarch64"
git-tree-sha1 = "0261da5276ab2d9578278c5bf271223f29387514"
os = "freebsd"

    [[Binutils.download]]
    sha256 = "8f7f289ac339c3583e3168726a4b8f5be23f38ca61e1bdc85f40a2c292be9a0b"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.45.0+0/Binutils.v2.45.0.aarch64-unknown-freebsd.tar.gz"
[[Binutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4e082e5a68f4a8342bfcba5d5bff9582e8c7a645"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "b1d9b7362be9abff215286a7022f08420c9acde660f1fb40a31b605ae6604858"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.45.0+0/Binutils.v2.45.0.armv6l-linux-gnueabihf.tar.gz"
[[Binutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "545e287ff0968756605b7f95a7ff13597eeb03f0"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "e537e25736496704c544968a69275a3ffedfb926ad780a8037272fa5b2225049"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.45.0+0/Binutils.v2.45.0.armv6l-linux-musleabihf.tar.gz"
[[Binutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ede9f114e8d98d169df61ca7b9c15955017152b7"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "fc0b14174d1e57f1633aa70ee206573b94f8453b007cdedb60bd5ca83529874c"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.45.0+0/Binutils.v2.45.0.armv7l-linux-gnueabihf.tar.gz"
[[Binutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ebbe114b020af7cf79715969e5cca33dfdb4853b"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "17eede32d396e64ccd88d88b8e84558023a9007d403fb4c2ca938d950b69cc95"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.45.0+0/Binutils.v2.45.0.armv7l-linux-musleabihf.tar.gz"
[[Binutils]]
arch = "i686"
git-tree-sha1 = "8f3b851791b5416d1324b2583a0a6904b2dd25a9"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "1b7c5207652f6b91d8db7d01265289313d29cea9d57f81f9bc39224eaead9d11"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.45.0+0/Binutils.v2.45.0.i686-linux-gnu.tar.gz"
[[Binutils]]
arch = "i686"
git-tree-sha1 = "dfb4f87487216559d06e10c3734c4af835259e39"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "0a7fb1f45f44485d7954b4e817dfa010f9b5ca0255dd3227512a284af94d3ff9"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.45.0+0/Binutils.v2.45.0.i686-linux-musl.tar.gz"
[[Binutils]]
arch = "powerpc64le"
git-tree-sha1 = "fcbe3b03607e16f4b9183aabaa69e292e6174c78"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "f6a53bb99f7e7289cafd1fa5357a2a63372eae64435e39871b4cb3a7cfad4de7"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.45.0+0/Binutils.v2.45.0.powerpc64le-linux-gnu.tar.gz"
[[Binutils]]
arch = "riscv64"
git-tree-sha1 = "b5ec730b6c8f50b7eb7b6721b2b793e5b9bb1d66"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "e30353e67ca6f1e0726200002127217ae481cd2ceb5a917a30354bcd1b55ac3e"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.45.0+0/Binutils.v2.45.0.riscv64-linux-gnu.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "4671cfb378ad21e25e7b3bc2a395f9bd55ab5d20"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "ad350eafbe8cabf466998ce85eae76bb9feebb23c2c5f8dd3d9b24d5c0c14764"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.45.0+0/Binutils.v2.45.0.x86_64-linux-gnu.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "020c23d56acfb30c58951126bea1e952e56887ec"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "f270a5f2602d4fcb94ca532e80a2d9442d95dea780f8a672d716454a964cafcf"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.45.0+0/Binutils.v2.45.0.x86_64-linux-musl.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "2a52f17bc21349dc19a039b7a4d7a2eece022460"
os = "freebsd"

    [[Binutils.download]]
    sha256 = "219191907bd89179baf5b0e04e327f1c27e37130efd2f6780237338e49af5895"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.45.0+0/Binutils.v2.45.0.x86_64-unknown-freebsd.tar.gz"
