[[Binutils]]
arch = "aarch64"
git-tree-sha1 = "31e4532ed5050b31cb431fdf8d88ac0fa15c2418"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "7e0fd32081608cd62a39caed95592e534fa719fbaa5cc80f1544d3125411aa01"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.43.0+0/Binutils.v2.43.0.aarch64-linux-gnu.tar.gz"
[[Binutils]]
arch = "aarch64"
git-tree-sha1 = "64a66de704bbc8942187c2ba171800981751db31"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "eb8852c530ec67eec5e56fb5d2788a62f3940141674b15eb57076f47d78e34af"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.43.0+0/Binutils.v2.43.0.aarch64-linux-musl.tar.gz"
[[Binutils]]
arch = "aarch64"
git-tree-sha1 = "76cb01f7725ef603465740f9fba897348085780a"
os = "freebsd"

    [[Binutils.download]]
    sha256 = "617ed58bf622cb3f535694447d915e0340cd5891983127bd35266961c1265001"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.43.0+0/Binutils.v2.43.0.aarch64-unknown-freebsd.tar.gz"
[[Binutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5738223180920b219bfbfdfbb372f7f0b3d9674e"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "67cca29e2bf9145b942d001983c269fcf683630df651dba25bf23225197f9973"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.43.0+0/Binutils.v2.43.0.armv6l-linux-gnueabihf.tar.gz"
[[Binutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a6c7304838427659c2c41943803357035f622653"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "a43fa74e2b5e3c6598ad4d0d3b8470c5bf2dc62b10d7462eaa58adcb05a2c8e9"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.43.0+0/Binutils.v2.43.0.armv6l-linux-musleabihf.tar.gz"
[[Binutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cf78276390e9eddfc18ca8c72e589a3fb1a08799"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "002b1714f9b5169746b21c68db3b7abcd690e30b4141e2830bd9ee14c344cf2a"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.43.0+0/Binutils.v2.43.0.armv7l-linux-gnueabihf.tar.gz"
[[Binutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c2beb8ae7cf3c32ecab343d5046e00f58d5e93f4"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "4597252f0344917e89c034675155dadbf88791144789e9b7654530391e9b9cad"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.43.0+0/Binutils.v2.43.0.armv7l-linux-musleabihf.tar.gz"
[[Binutils]]
arch = "i686"
git-tree-sha1 = "4e23764e0774f95fe93e158377192f8decd272ea"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "02a5c952840faaa662ce18b9a0ad7a6a1be9f3c6f5a124730045cd9e7e8de166"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.43.0+0/Binutils.v2.43.0.i686-linux-gnu.tar.gz"
[[Binutils]]
arch = "i686"
git-tree-sha1 = "36e036655f04ad5464af306867651667a5cb4a20"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "e84ea04888cb7534f4d3124eab76aed288738326dc0a13661c30a0a8358eeb67"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.43.0+0/Binutils.v2.43.0.i686-linux-musl.tar.gz"
[[Binutils]]
arch = "powerpc64le"
git-tree-sha1 = "46ea025d261bf4d8a37d3cd4331be9c158b47ab5"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "16a1968582eadf0e6112a0ce62b6bf93e1b10be9e477add11bc97db8f0111e56"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.43.0+0/Binutils.v2.43.0.powerpc64le-linux-gnu.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "856c65cba4eee3e6f9e1cb1c0b88f29dee0ab762"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "035c7d85915fb4975e1aaad077e722b2a3da897525d3e9471376552ce1b2469c"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.43.0+0/Binutils.v2.43.0.x86_64-linux-gnu.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "f7efc6979dba7dd1e8f2fb48c917140d3f4aa77b"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "4d1866f2c40f163fa0d0d125b4e2bd2bcbdfc527f2488d79a14c6da2fa31dc96"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.43.0+0/Binutils.v2.43.0.x86_64-linux-musl.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "a8d1369b7f7ab0eeeeea2bf3482626d7609e3f59"
os = "freebsd"

    [[Binutils.download]]
    sha256 = "65f21b8c4fb2162f74f9e8cb79131a4f2df61ab20529dc0e80cf38d6cede8118"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.43.0+0/Binutils.v2.43.0.x86_64-unknown-freebsd.tar.gz"
