[[Binutils]]
arch = "aarch64"
git-tree-sha1 = "7c822d5ce06bd29dae00be38766019217a48ee98"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "2ac46fccfb38baf110b246f06bbaeb35582d0743acb0779fa857a6d15560b430"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.41.0+0/Binutils.v2.41.0.aarch64-linux-gnu.tar.gz"
[[Binutils]]
arch = "aarch64"
git-tree-sha1 = "f71ab3df373b881d0e5570a8b1690e25b7fa3bdd"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "e483f9431c3db1d4de63ffe04fdd4967b33cf37c748bea7930c99274327c8ef0"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.41.0+0/Binutils.v2.41.0.aarch64-linux-musl.tar.gz"
[[Binutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "18a4490d01475f64c198d36ee67fc138d9a8fa52"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "d4dbb5a46803f4ffa9ca299a71d694075c3d064f04a53e64aedc7324419be7d5"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.41.0+0/Binutils.v2.41.0.armv6l-linux-gnueabihf.tar.gz"
[[Binutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "356519d5f391d62fcf213144e8adbda3e5a076f0"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "720f40f0938fa93685252d7c4c3e397b7fb7ca2903b5e896d7fe9df038da510d"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.41.0+0/Binutils.v2.41.0.armv6l-linux-musleabihf.tar.gz"
[[Binutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "63bd6cd99e8a4191bf57dbfd4dfc4e797210f36e"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "4f571a0ceec0f4eb5ed09ac468723ba07f83668e5b4c971fb63f4fda50dcc1e8"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.41.0+0/Binutils.v2.41.0.armv7l-linux-gnueabihf.tar.gz"
[[Binutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c8cd41da3a18db88d27c8aab1fc3fdb6b62622cc"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "75fefb60671e5e5e5d6faf6be25b3f68305d52335e4693fd4cbbe0fad373d27d"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.41.0+0/Binutils.v2.41.0.armv7l-linux-musleabihf.tar.gz"
[[Binutils]]
arch = "i686"
git-tree-sha1 = "1887cfb35f5e017fc88d93ff506d3cb8a5a65969"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "987e6782d4c77532c766302d93e3e9013737a02a09734f374f9530bf32e1c616"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.41.0+0/Binutils.v2.41.0.i686-linux-gnu.tar.gz"
[[Binutils]]
arch = "i686"
git-tree-sha1 = "09daef89182760bad6a1490984afa8522857bc4e"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "423243a705522e7405d7e64f7509a59296c7902a4f3fbb73d05a44e5def35690"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.41.0+0/Binutils.v2.41.0.i686-linux-musl.tar.gz"
[[Binutils]]
arch = "powerpc64le"
git-tree-sha1 = "8b63b921f789286cd310abc84e08d95663599131"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "3ba5ce19059550f7d56c7561ed3ad4cca86735abe11da9fbe053443fee0065c4"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.41.0+0/Binutils.v2.41.0.powerpc64le-linux-gnu.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "6e06e78828d52bb084a4075d044800fe5c152ac6"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "ba473f0ffe3ae80c7a336e6dc541b69851484dd5e47ffe27fac6910a3837f111"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.41.0+0/Binutils.v2.41.0.x86_64-linux-gnu.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "6c189760fdff6e65c15259121ca463809ae850f2"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "18aab35fd7cc0749df5c628f0447347a23bcf4a80a201daade5d93ee38b8d614"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.41.0+0/Binutils.v2.41.0.x86_64-linux-musl.tar.gz"
