[[Binutils]]
arch = "aarch64"
git-tree-sha1 = "60ccbe140a32730cfed6fe7c6f035795744f87cb"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "c63d1f61b319a0256db0948f525397dc0c69b20af4d26ecbf4ede0f6c92a1161"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.44.0+0/Binutils.v2.44.0.aarch64-linux-gnu.tar.gz"
[[Binutils]]
arch = "aarch64"
git-tree-sha1 = "a3cfe5cbe2daa9bc14791afe5014e52c89b4c712"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "18371e6c484cc9fbbe43b2df67a625dcb8ec41c7f1a52110b176c7521fe2b526"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.44.0+0/Binutils.v2.44.0.aarch64-linux-musl.tar.gz"
[[Binutils]]
arch = "aarch64"
git-tree-sha1 = "322ba93c672da1ba503319f83dc6aff789afbc67"
os = "freebsd"

    [[Binutils.download]]
    sha256 = "9fdfe57276c52ccdcef475dfbe0fdaed484c0839468e48bdfef46257df3b386f"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.44.0+0/Binutils.v2.44.0.aarch64-unknown-freebsd.tar.gz"
[[Binutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "113b6d1f78232bfec57dca1507ad2515efbfebf4"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "02445c4022b9d5224a67060f210c927a0afd1078db312f02730688340f66250e"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.44.0+0/Binutils.v2.44.0.armv6l-linux-gnueabihf.tar.gz"
[[Binutils]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e707c0140d822125eb0eb836934eaa27d05c60e4"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "507535d4783cc6c0a880f5df51c7ad6c32f53f0772f92e8ad3baf4133ffca193"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.44.0+0/Binutils.v2.44.0.armv6l-linux-musleabihf.tar.gz"
[[Binutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "b052759a73214ccf56f20bdf19f5b9998938d537"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "023c8201eeb5a8baa03df2dad40fa1a6b2435f6387624d13a2061db21e792cb1"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.44.0+0/Binutils.v2.44.0.armv7l-linux-gnueabihf.tar.gz"
[[Binutils]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e518de8341c9ca66f4cd63b2d5764c308c7c4f86"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "0acdb3b72b492dc4483ef4bea44a90adbba19561620b270f9ed19a1a4a5eef1f"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.44.0+0/Binutils.v2.44.0.armv7l-linux-musleabihf.tar.gz"
[[Binutils]]
arch = "i686"
git-tree-sha1 = "bb80b74f0989b52d08b139e7be74a13872963f92"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "85fcefb3e5ebda54017eee4f6e2bbd212c5c9eae3dc6309d3f78afd57dddff5c"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.44.0+0/Binutils.v2.44.0.i686-linux-gnu.tar.gz"
[[Binutils]]
arch = "i686"
git-tree-sha1 = "feec7aec51c1778487542504be1468211006e4b9"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "6899f9b939232fa319ac940c361c6dc094256fa56ad1799875262cc8854a6f66"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.44.0+0/Binutils.v2.44.0.i686-linux-musl.tar.gz"
[[Binutils]]
arch = "powerpc64le"
git-tree-sha1 = "da2716cfa7606c42ef14780bf859d6c8ca68d979"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "4d988090110238640ce8642c16da7db0ee953f0747be95520906929c9e5dcd71"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.44.0+0/Binutils.v2.44.0.powerpc64le-linux-gnu.tar.gz"
[[Binutils]]
arch = "riscv64"
git-tree-sha1 = "f65835aae20d651b1ef0a09fa661a9fbe9a642bf"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "3a2c43e8fd985365cdefe989a1987a874d74f98c7108f943990826650ff1a38d"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.44.0+0/Binutils.v2.44.0.riscv64-linux-gnu.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "2c5bcb5061eb916c7ea2b0d04cefadd31572c4eb"
libc = "glibc"
os = "linux"

    [[Binutils.download]]
    sha256 = "957796687b89f07bd3e7b1a52e2c0f0bc3bb3164ab6a03bb2ce62de1bd17202e"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.44.0+0/Binutils.v2.44.0.x86_64-linux-gnu.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "1d5446f6556f810dec5102a5fd1d5de126d89ecb"
libc = "musl"
os = "linux"

    [[Binutils.download]]
    sha256 = "047cd8247e8d8ccc7deb385f19d5d5ccedfb6eef3dfa2683cf39e56c0fbb3e9d"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.44.0+0/Binutils.v2.44.0.x86_64-linux-musl.tar.gz"
[[Binutils]]
arch = "x86_64"
git-tree-sha1 = "90bd4105bc7538e85d8e2acdce6e8497b4002172"
os = "freebsd"

    [[Binutils.download]]
    sha256 = "050994c57acefb4d2454b5c97f0e8629b9d2b67fde7465bbf0af55cde4ca4126"
    url = "https://github.com/JuliaBinaryWrappers/Binutils_jll.jl/releases/download/Binutils-v2.44.0+0/Binutils.v2.44.0.x86_64-unknown-freebsd.tar.gz"
